import json
import re
from pathlib import Path

import urllib3

# Downloading the .proto file from the GitHub repository
url = "https://raw.githubusercontent.com/fivetran/zetasql-snowflake/master/zetasql/public/builtin_function.proto"
http = urllib3.PoolManager()
response = http.request("GET", url)
proto_content = response.data.decode("utf-8")

# Extracting all keys that start with "FN_" from the .proto file
# Assuming these keys are defined in a specific way in the .proto file, like "FN_ADD_DOUBLE = 1;"
# Using a regular expression to find all occurrences
fn_keys = re.findall(r"FN_[A-Z_]+", proto_content)

# Removing the "FN_" prefix from each key
keys_without_prefix = [key[3:] for key in fn_keys]

# Removing duplicates by converting the list to a set, then back to a list
keys_unique = list(set(keys_without_prefix))

# Sorting the list for better readability
keys_unique.sort()

# Overwrite file in ../src/harlequin_bigquery/functions.py
# creating it if it doesn't exist
# and write the keys_unique list to it
path = Path(__file__).parents[1] / "src" / "harlequin_bigquery" / "functions.py"
prefix = "# Autogenerated using `scripts/parse_builtins.py`\n\n"

with path.open("w+") as file:
    file.write(prefix + f"BUILTIN_FUNCTIONS = {json.dumps(keys_unique, indent=4)}\n")
